### ISSUE TITLE
메인 배너 이미지 추가 

### ISSUE THREAD

**Issue by daamable-sknk** [team-durumi/didkorea#23]
고객 요청으로 메인 하단에 배너 이미지 추가를 요청드립니다. 

- 이미지 정보는 front.yml 의 아래 항목에 적어두었습니다.

```
banners:
  - title: 'D.I.D KOGYO'
    image: /slide1.png
    link: https://www.did-coltd.com/english/
  - title: 'D.I.D DIGITAL CATALOG 2020'
    image: /slide2.png
    link: https://www.did-daido.co.jp/documents/ebooks/catalog/english2020/
  - title: 'D.I.D CO.LTD.'
    image: /slide3.png
    link: https://www.did-coltd.com/
    # 메인 배너에 새로운 이미지를 추가해주세요. title, image, link 정보는 위에 입력했습니다. 
    # 새로운 이미지는 다음 링크에서 다운받아서 slide3 파일로 저장해주시면 될 것 같습니다. 
    # https://www.did-daido.co.jp/assets/img/top/bnr_im.png
    # 이 이미지는 이 사이트 하단의 배너 이미지에서 가져왔습니다. https://www.did-daido.co.jp/index.html 

```

- 배너 이미지는 기존 2개에서 3개로 추가해주시면 좋을 것 같습니다. 아래 이미지는 제가 임의로 배치해 본것이에요. 맨 오른쪽 세 번째 이미지가 새로 추가해보고자 한 것입니다. 
  - img div class 를 `col-md-6`에서 `col-md-4` 정도로 맞춰보니 딱 맞는 것 같네요 ㅎㅎ 

<img width="1010" alt="스크린샷 2022-10-10 오후 3 36 57" src="https://user-images.githubusercontent.com/75353630/194809817-3f22020a-1915-4070-895b-461a9c365c24.png">
