### ISSUE TITLE
취급품목 이미지 사이즈 높이를 통일합니다. 

### ISSUE THREAD

**Issue by daamable** [team-durumi/didkorea#4]
![스크린샷 2020-03-26 오전 9 06 40](https://user-images.githubusercontent.com/39326928/77597266-a3ce8700-6f41-11ea-92b5-5cef052d2c99.png)

마지막으로 요거 반영해주시면 좋겠습니다...!

**Comment by woonjjang** [comment]
```
# 담과 함께 홈에 노출될 항목과 제목 매칭해야 함.

featuredProducts:
  - title: '일본수입(DID) RS체인'
    image: /products/01/src-01-modify.png
    link: /product/01-standard-roller-chain
  - title: 'HI-PWR-S 롤러체인'
    image: /products/02/upc-01.jpg
    link: /product/02-ultimate-power-chain-series
  - title: 'HK타입 롤러체인'
    image: /products/02/upc-02.jpg
    link: /product/02-ultimate-power-chain-series
  - title: 'HI-PWR-SHK 롤러체인'
    image: /products/02/upc-03.jpg
    link: /product/02-ultimate-power-chain-series
  - title: 'X-RING체인, O-RING체인'
    image: /products/03/ulc-01.jpg
    link: /product/03-ultimate-life-chain-series
  - title: 'Fit X-RING 체인'
    image: /products/03/ulc-02.jpg
    link: /product/03-ultimate-life-chain-series
  - title: 'Sintered 비지니스 롤러체인'
    image: /products/03/ulc-03.jpg
    link: /product/03-ultimate-life-chain-series
  - title: 'Nickel Plated 체인'
    image: /products/04/erc-01.jpg
    link: /04-environmental-resistant-chain-series
  - title: '하이가드 체인'
    image: /products/04/erc-02.jpg
    link: /04-environmental-resistant-chain-series
  - title: '더블가드 체인'
    image: /products/04/erc-03.jpg
    link: /04-environmental-resistant-chain-series
  - title: '스테인리스 스틸 체인(SS/SSK)'
    image: /products/04/erc-04-modify.jpg
    link: /04-environmental-resistant-chain-series
  - title: 'SN 트리트먼트 체인(SN)'
    image: /products/04/erc-04-modify.jpg
    link: /04-environmental-resistant-chain-series
  - title: '스테인리스 스틸 X-RING 체인(SN)'
    image: /products/04/erc-05.jpg
    link: /04-environmental-resistant-chain-series
  - title: '저온 저항 체인'
    image: /products/04/erc-06.jpg'
    link: /04-environmental-resistant-chain-series
```
@daamable 이미지 맞추면서 총 14개 제품 이름을 적어 놓았어요. 기존에 노출되고 있던 것은 한글명칭과 이미지가 약간씩 달랐던 거에요. product-terms.yml 보면서 제품이미지랑 확인이 필요해요. 

14개 제품이어서 2개가 줄 아래로 노출될테니깐, 빠져도 되는 항목이 있으면 알려줘도 되요. 

@sunparty 링크 추가해 놨습니다. 연결부탁해요.
